### ISSUE TITLE
Issue with Bower link in READ.ME

### ISSUE THREAD

**Issue by larrybabb** [Collaborne/paper-expansion-panel#1]
It seems like you may have an issue with the "Bower" link in your READ.ME file.  It seems to point to a version that is in a different git repository and it is not equivalent to your version in neither structure or content.  I noticed the same  behavior in your paper-chip repo as well.

Bower link on paper-expansion-panel README.md points to [![Bower version](https://badge.fury.io/bo/paper-expansion-panel.svg)](http://badge.fury.io/bo/paper-expansion-panel) which goes to https://github.com/ardf69/paper-expansion-panel and this is not the same repo.

Also, check out your paper-chip project with the same issue.

**Comment by ronnyroeller** [comment]
Thanks for pointing out this issue.
