### ISSUE TITLE
A Bower Install issue

### ISSUE THREAD

**Issue by larrybabb** [Collaborne/paper-expansion-panel#2]
When you try to use

`bower install Collaborne/paper-expansion-element --save`
               
You get

>`> not-cached https://github.com/Collaborne/paper-expansion-element.git#*`
>`> resolve https://github.com/Collaborne/paper-expansion-element.git#*`
>`>ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/Collaborne/paper-expansion-element.git", exit code of #128 remote: Repository not found. fatal: repository 'https://github.com/Collaborne/paper-expansion-element.git/' not found`

Your paper-chip repo works fine when using the equivalent bower install command.

Can you fix or provide guidance on what I might be doing wrong?

**Comment by larrybabb** [comment]
This looks like my environment. sorry for the disruption.

**Comment by ronnyroeller** [comment]
@larrybabb It's actually `-panel` instead of `-element`:
```
bower install paper-expansion-panel
```

**Comment by larrybabb** [comment]
got it. thanks.
